remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Ági Villányi
description: |-
  <p><em>Contact</em> agivilla @ mit.edu</p>
  <p><em>Personal (p)articles</em> any neutral set</p>
logo: me.png
