remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Ági Villányi
description: |-
  <em>Contact<\em> agivilla @ mit.edu
  <em>Personal (p)articles<\em> any neutral set
logo: me.png
